name: using artificat
on: [push]

env:
  FILE_NAME: hello-server

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build ${{ env.FILE_NAME  }} for ubuntu
      run: go build ${{env.FILE_NAME}}.go
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: linux
        path: ./${{env.FILE_NAME}}
  test:
    name: test- linux
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.1
      with:
        name: linux

    - name: Test ${{env.FILE_NAME}}
      run: source ./test.sh
            
            
    
  
