name: Auto Merge Owner PR 

on:
  pull_request:
    types: [opened, reopened] 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'


  merge:
    if: github.actor == 'dsudhakar26'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AwesomeHamster/actions-auto-approve@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
   
      
    

      
