name: Auto Merge Owner PR 

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.1.1

    - name: flake8 and pylint
      run: |
        pip install -r requirement.txt
        flake8 --ignore=E501,E231  *.py tests/*.py
        pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py

    - name: unit test
      run: python -m unittest --verbose --failfast

  merge:
    if: github.actor == 'dsudhakar26'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hmarr/auto-approve-actions@v2.0.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
    - uses:  managedkaos/merge-pull-request@v1.2
      env:
        GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
      
    

      
