name: Environment Variable demo
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: 'Workspace Environment Variable'
  OVER_RIDE: 'WorkSpace Override'
on: pull_request
jobs:
  ubuntu:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'JOB Environment Variable'
      OVER_RIDE: 'Job Override'
    runs-on: ubuntu-latest
    steps:
    - name: print Environment variable
      env:
        STEP_ENVIRONMENT_VARIABLE: 'Step Environment Variable'
        OVER_RIDE: 'Step Override'
      run: |
        echo " Accessing Environment Variable through bash script variable"
        echo " 1. $WORKSPACE_ENVIRONMENT_VARIABLE"
        echo " 2. $JOB_ENVIRONMENT_VARIABLE "
        echo " 3. $STEP_ENVIRONMENT_VARIABLE "
        echo " 4. $OVER_RIDE "
        echo " -------------------------------------"
        echo " Accessing the Env varialbes through the YAML syntax"
        echo "5. ${{env.WORKSPACE_ENVIRONMENT_VARIABLE}}"
        echo "6. ${{env.JOB_ENVIRONMENT_VARIABLE}}"
        echo "7. ${{env.STEP_ENVIRONMENT_VARIABLE}}"
        echo "8. ${{env.OVER_RIDE}}"

        
        
      
        
        
      
    
