name: Environment Variable demo
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: "Workspace Environment Variable"
  OVER_RIDE: "WorkSpace Override"
on: push
jobs:
  ubuntu:
    env:
      JOB_ENVIRONMENT_VARIABLE: "JOB Environment Variable"
      OVERRIDE: "Job Override"
    runs-on: ubuntu-latest
    steps:
    - name: print Environment variable
      env:
        STEP_ENVIRONMENT_VARIABLE: "Step Environment Variable"
        ORVER_RIDE: "Step Override"
      run: |
        echo " Accessing through bash script variable"
        echo " 1. $WORKSPACE_ENVIRONMENT_VARIABLE"
        echo " 2. $JOB_ENVIRONMENT_VARIABLE "
        echo " 3. $STEP_ENVIRONMENT_VARIABLE "
        echo " 4. $OVER_RIDE "
        echo " -------------------------------------"
        echo " Accessing the Env varialbes through the YAML syntax"
        echo "5. ${{WORKSPACE_ENVIRONMENT_VARIABLE}}"
        echo "6. ${{JOB_ENVIRONMENT_VARIABLE}}"
        echo "7. ${{STEP_ENVIRONMENT_VARIABLE}}"
        echo "8. ${{OVER_RIDE}}"
        
        
      
    
